import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import api from '../../services/api';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement,
  PointElement,
  LineElement,
} from 'chart.js';
import { Bar, Doughnut, Line } from 'react-chartjs-2';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement,
  PointElement,
  LineElement
);

const AdminReports = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [reportType, setReportType] = useState('ticket_summary');
  const [dateRange, setDateRange] = useState('30');
  const [generating, setGenerating] = useState(false);
  const [reportData, setReportData] = useState(null);
  const [showReportModal, setShowReportModal] = useState(false);

  const reportTypes = [
    { value: 'ticket_summary', label: 'Ticket Summary Report' },
    { value: 'ticket_trend', label: 'Ticket Trend Analysis' },
    { value: 'hardware_summary', label: 'Hardware Inventory Report' },
    { value: 'hardware_movement', label: 'Hardware Movement Report' },
    { value: 'agent_performance', label: 'Agent Performance Report' },
    { value: 'department_summary', label: 'Department Summary Report' },
    { value: 'sla_compliance', label: 'SLA Compliance Report' },
    { value: 'category_analysis', label: 'Category Analysis Report' },
  ];

  useEffect(() => {
    fetchReportData();
  }, []);

  const fetchReportData = async () => {
    setLoading(true);
    setError('');
    try {
      const response = await api.get('/admin/reports/summary/');
      setReportData(response);
    } catch (error) {
      
      if (error.message?.includes('401') || error.message?.includes('login')) {
        navigate('/authPages/login');
        return;
      }
      setError('Failed to load report data. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = async () => {
    setGenerating(true);
    setError('');
    try {
      const response = await api.post('/admin/reports/generate/', {
        report_type: reportType,
        date_range: dateRange,
      });
      setReportData(response);
      setShowReportModal(true);
    } catch (error) {
    
      if (error.message?.includes('401') || error.message?.includes('login')) {
        navigate('/authPages/login');
        return;
      }
      setError('Failed to generate report. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  // Professional PDF Report
  const handleExportPDF = () => {
    setGenerating(true);
    try {
      const doc = new jsPDF('p', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      
      // === HEADER ===
      doc.setFillColor(13, 71, 161);
      doc.rect(0, 0, pageWidth, 45, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text('SYSTEM REPORT', pageWidth / 2, 28, { align: 'center' });
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, 38, { align: 'center' });
      
      let yPos = 55;
      
      // === REPORT INFORMATION ===
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('REPORT INFORMATION', 14, yPos);
      yPos += 6;
      
      doc.setDrawColor(0, 0, 0);
      doc.setLineWidth(0.3);
      doc.line(14, yPos, pageWidth - 14, yPos);
      yPos += 6;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(80, 80, 80);
      doc.text(`Report Type: ${reportTypes.find(t => t.value === reportType)?.label || reportType}`, 14, yPos);
      yPos += 6;
      doc.text(`Date Range: ${dateRange} days`, 14, yPos);
      yPos += 6;
      doc.text(`Generated By: ${user?.full_name || user?.username || 'System'}`, 14, yPos);
      yPos += 10;
      
      // === SUMMARY STATISTICS ===
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('SUMMARY STATISTICS', 14, yPos);
      yPos += 6;
      
      doc.setDrawColor(0, 0, 0);
      doc.setLineWidth(0.3);
      doc.line(14, yPos, pageWidth - 14, yPos);
      yPos += 6;
      
      // Summary stats in 2 columns
      const summaryStats = [
        ['Total Tickets', reportData?.total_tickets || 0],
        ['Resolved Tickets', reportData?.resolved_tickets || 0],
        ['Open Tickets', reportData?.open_tickets || 0],
        ['SLA Breached', reportData?.sla_breached || 0],
      ];
      
      summaryStats.forEach(([label, value], index) => {
        const col = index % 2;
        const row = Math.floor(index / 2);
        const xPos = 14 + (col * 80);
        const yPos2 = yPos + (row * 10);
        
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(80, 80, 80);
        doc.text(`${label}:`, xPos, yPos2);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text(String(value), xPos + 35, yPos2);
      });
      
      yPos += (Math.ceil(summaryStats.length / 2) * 10) + 10;
      
      // === STATUS BREAKDOWN ===
      if (reportData?.status_breakdown?.length > 0) {
        if (yPos > pageHeight - 70) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('STATUS BREAKDOWN', 14, yPos);
        yPos += 6;
        
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.3);
        doc.line(14, yPos, pageWidth - 14, yPos);
        yPos += 6;
        
        const statusRows = reportData.status_breakdown.map(item => [
          formatStatusLabel(item.name),
          item.count
        ]);
        
        autoTable(doc, {
          startY: yPos,
          head: [['Status', 'Count']],
          body: statusRows,
          theme: 'striped',
          headStyles: { 
            fillColor: [13, 71, 161], 
            textColor: [255, 255, 255], 
            fontStyle: 'bold',
            fontSize: 10,
          },
          styles: { fontSize: 9 },
          columnStyles: {
            0: { cellWidth: 70 },
            1: { cellWidth: 30, halign: 'center' },
          },
          margin: { left: 14, right: 14 },
        });
        yPos = doc.lastAutoTable.finalY + 10;
      }
      
      // === CATEGORY BREAKDOWN ===
      if (reportData?.category_breakdown?.length > 0) {
        if (yPos > pageHeight - 70) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('CATEGORY BREAKDOWN', 14, yPos);
        yPos += 6;
        
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.3);
        doc.line(14, yPos, pageWidth - 14, yPos);
        yPos += 6;
        
        const categoryRows = reportData.category_breakdown.map(item => [
          item.name || 'Uncategorized',
          item.count
        ]);
        
        autoTable(doc, {
          startY: yPos,
          head: [['Category', 'Count']],
          body: categoryRows,
          theme: 'striped',
          headStyles: { 
            fillColor: [13, 71, 161], 
            textColor: [255, 255, 255], 
            fontStyle: 'bold',
            fontSize: 10,
          },
          styles: { fontSize: 9 },
          columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 30, halign: 'center' },
          },
          margin: { left: 14, right: 14 },
        });
        yPos = doc.lastAutoTable.finalY + 10;
      }
      
      // === SLA BREAKDOWN ===
      if (reportData?.sla_breakdown?.length > 0) {
        if (yPos > pageHeight - 70) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('SLA BREAKDOWN', 14, yPos);
        yPos += 6;
        
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.3);
        doc.line(14, yPos, pageWidth - 14, yPos);
        yPos += 6;
        
        const slaRows = reportData.sla_breakdown.map(item => [
          item.name,
          item.count
        ]);
        
        autoTable(doc, {
          startY: yPos,
          head: [['SLA Status', 'Count']],
          body: slaRows,
          theme: 'striped',
          headStyles: { 
            fillColor: [13, 71, 161], 
            textColor: [255, 255, 255], 
            fontStyle: 'bold',
            fontSize: 10,
          },
          styles: { fontSize: 9 },
          columnStyles: {
            0: { cellWidth: 70 },
            1: { cellWidth: 30, halign: 'center' },
          },
          margin: { left: 14, right: 14 },
        });
        yPos = doc.lastAutoTable.finalY + 10;
      }
      
      // === TICKET TREND ===
      if (reportData?.ticket_trend?.length > 0) {
        if (yPos > pageHeight - 70) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('TICKET TREND', 14, yPos);
        yPos += 6;
        
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.3);
        doc.line(14, yPos, pageWidth - 14, yPos);
        yPos += 6;
        
        const trendRows = reportData.ticket_trend.map(item => [
          item.day || item.date || 'N/A',
          item.count || 0
        ]);
        
        autoTable(doc, {
          startY: yPos,
          head: [['Date', 'Tickets']],
          body: trendRows,
          theme: 'striped',
          headStyles: { 
            fillColor: [13, 71, 161], 
            textColor: [255, 255, 255], 
            fontStyle: 'bold',
            fontSize: 10,
          },
          styles: { fontSize: 9 },
          columnStyles: {
            0: { cellWidth: 50 },
            1: { cellWidth: 30, halign: 'center' },
          },
          margin: { left: 14, right: 14 },
        });
        yPos = doc.lastAutoTable.finalY + 10;
      }
      
      // === FOOTER ===
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(7);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 30, pageHeight - 8);
        doc.text('Generated by System Report Tool', 14, pageHeight - 8);
      }
      
      doc.save(`System_Report_${new Date().toISOString().split('T')[0]}.pdf`);
      
    } catch (error) {
   
      setError('Failed to generate PDF report. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  // Professional Excel Report
  const handleExportExcel = () => {
    setGenerating(true);
    try {
      const wb = XLSX.utils.book_new();
      
      // === SHEET 1: SUMMARY ===
      const summaryData = [
        ['SYSTEM REPORT'],
        [`Generated: ${new Date().toLocaleString()}`],
        [`Report Type: ${reportTypes.find(t => t.value === reportType)?.label || reportType}`],
        [`Date Range: ${dateRange} days`],
        [],
        ['SUMMARY STATISTICS'],
        ['Metric', 'Value'],
        ['Total Tickets', reportData?.total_tickets || 0],
        ['Resolved Tickets', reportData?.resolved_tickets || 0],
        ['Open Tickets', reportData?.open_tickets || 0],
        ['SLA Breached', reportData?.sla_breached || 0],
      ];
      
      const ws1 = XLSX.utils.aoa_to_sheet(summaryData);
      ws1['!cols'] = [{ wch: 25 }, { wch: 20 }];
      XLSX.utils.book_append_sheet(wb, ws1, 'Summary');
      
      // === SHEET 2: STATUS BREAKDOWN ===
      if (reportData?.status_breakdown?.length > 0) {
        const statusData = [
          ['STATUS BREAKDOWN'],
          ['Status', 'Count']
        ];
        reportData.status_breakdown.forEach(item => {
          statusData.push([formatStatusLabel(item.name), item.count]);
        });
        
        const ws2 = XLSX.utils.aoa_to_sheet(statusData);
        ws2['!cols'] = [{ wch: 25 }, { wch: 15 }];
        XLSX.utils.book_append_sheet(wb, ws2, 'Status Breakdown');
      }
      
      // === SHEET 3: CATEGORY BREAKDOWN ===
      if (reportData?.category_breakdown?.length > 0) {
        const categoryData = [
          ['CATEGORY BREAKDOWN'],
          ['Category', 'Count']
        ];
        reportData.category_breakdown.forEach(item => {
          categoryData.push([item.name || 'Uncategorized', item.count]);
        });
        
        const ws3 = XLSX.utils.aoa_to_sheet(categoryData);
        ws3['!cols'] = [{ wch: 30 }, { wch: 15 }];
        XLSX.utils.book_append_sheet(wb, ws3, 'Category Breakdown');
      }
      
      // === SHEET 4: SLA BREAKDOWN ===
      if (reportData?.sla_breakdown?.length > 0) {
        const slaData = [
          ['SLA BREAKDOWN'],
          ['Status', 'Count']
        ];
        reportData.sla_breakdown.forEach(item => {
          slaData.push([item.name, item.count]);
        });
        
        const ws4 = XLSX.utils.aoa_to_sheet(slaData);
        ws4['!cols'] = [{ wch: 25 }, { wch: 15 }];
        XLSX.utils.book_append_sheet(wb, ws4, 'SLA Breakdown');
      }
      
      // === SHEET 5: TICKET TREND ===
      if (reportData?.ticket_trend?.length > 0) {
        const trendData = [
          ['TICKET TREND'],
          ['Date', 'Tickets']
        ];
        reportData.ticket_trend.forEach(item => {
          trendData.push([item.day || item.date || 'N/A', item.count || 0]);
        });
        
        const ws5 = XLSX.utils.aoa_to_sheet(trendData);
        ws5['!cols'] = [{ wch: 20 }, { wch: 15 }];
        XLSX.utils.book_append_sheet(wb, ws5, 'Ticket Trend');
      }
      
      // Generate and download
      const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
      const blob = new Blob([wbout], { type: 'application/octet-stream' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `System_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
      
    } catch (error) {
     
      setError('Failed to generate Excel report. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const formatStatusLabel = (status) => {
    const labels = {
      'new': 'New',
      'open': 'Open',
      'in_progress': 'In Progress',
      'pending_customer': 'Pending Customer',
      'pending_third_party': 'Pending Third Party',
      'resolved': 'Resolved',
      'closed': 'Closed',
      'canceled': 'Canceled',
    };
    return labels[status] || status || 'Unknown';
  };

  const ticketTrendData = {
    labels: reportData?.ticket_trend?.map(item => item.day || item.date || '') || [],
    datasets: [
      {
        label: 'Tickets Created',
        data: reportData?.ticket_trend?.map(item => item.count || 0) || [],
        fill: true,
        backgroundColor: 'rgba(59, 130, 246, 0.15)',
        borderColor: '#3b82f6',
        tension: 0.4,
        pointBackgroundColor: '#3b82f6',
        pointBorderColor: '#ffffff',
        pointBorderWidth: 2,
        pointRadius: 4,
      },
    ],
  };

  const ticketTrendOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: false,
      },
      tooltip: {
        backgroundColor: '#ffffff',
        titleColor: '#1e293b',
        bodyColor: '#1e293b',
        borderColor: '#e2e8f0',
        borderWidth: 1,
        cornerRadius: 6,
        padding: 12,
      }
    },
    scales: {
      y: {
        beginAtZero: true,
        ticks: {
          stepSize: 1,
          font: { size: 11 },
          color: '#64748b',
        },
        grid: { color: 'rgba(100, 116, 139, 0.1)' },
      },
      x: {
        ticks: { font: { size: 11 }, color: '#64748b' },
        grid: { display: false },
      },
    },
  };

  const statusChartData = {
    labels: reportData?.status_breakdown?.map(item => formatStatusLabel(item.name)) || [],
    datasets: [
      {
        data: reportData?.status_breakdown?.map(item => item.count || 0) || [],
        backgroundColor: [
          'rgba(59, 130, 246, 0.85)',
          'rgba(99, 102, 241, 0.85)',
          'rgba(245, 158, 11, 0.85)',
          'rgba(139, 92, 246, 0.85)',
          'rgba(236, 72, 153, 0.85)',
          'rgba(16, 185, 129, 0.85)',
          'rgba(107, 114, 128, 0.85)',
          'rgba(239, 68, 68, 0.85)',
        ],
        borderColor: '#ffffff',
        borderWidth: 2,
      },
    ],
  };

  const statusChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'bottom',
        labels: {
          font: { size: 10 },
          color: '#64748b',
          padding: 8,
          usePointStyle: true,
          pointStyle: 'circle',
        },
      },
      tooltip: {
        backgroundColor: '#ffffff',
        titleColor: '#1e293b',
        bodyColor: '#1e293b',
        borderColor: '#e2e8f0',
        borderWidth: 1,
        cornerRadius: 6,
        padding: 12,
        callbacks: {
          label: function(context) {
            const total = context.dataset.data.reduce((a, b) => a + b, 0);
            const percentage = total > 0 ? Math.round((context.parsed / total) * 100) : 0;
            return `${context.label}: ${context.parsed} (${percentage}%)`;
          }
        }
      }
    },
    cutout: '70%',
  };

  const categoryChartData = {
    labels: reportData?.category_breakdown?.map(item => item.name || 'Uncategorized') || [],
    datasets: [
      {
        label: 'Tickets by Category',
        data: reportData?.category_breakdown?.map(item => item.count || 0) || [],
        backgroundColor: [
          'rgba(59, 130, 246, 0.85)',
          'rgba(99, 102, 241, 0.85)',
          'rgba(139, 92, 246, 0.85)',
          'rgba(168, 85, 247, 0.85)',
          'rgba(217, 70, 239, 0.85)',
          'rgba(236, 72, 153, 0.85)',
          'rgba(244, 63, 94, 0.85)',
          'rgba(16, 185, 129, 0.85)',
        ],
        borderColor: [
          'rgba(59, 130, 246, 1)',
          'rgba(99, 102, 241, 1)',
          'rgba(139, 92, 246, 1)',
          'rgba(168, 85, 247, 1)',
          'rgba(217, 70, 239, 1)',
          'rgba(236, 72, 153, 1)',
          'rgba(244, 63, 94, 1)',
          'rgba(16, 185, 129, 1)',
        ],
        borderWidth: 1,
        borderRadius: 4,
      },
    ],
  };

  const categoryChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: false,
      },
      tooltip: {
        backgroundColor: '#ffffff',
        titleColor: '#1e293b',
        bodyColor: '#1e293b',
        borderColor: '#e2e8f0',
        borderWidth: 1,
        cornerRadius: 6,
        padding: 12,
      }
    },
    scales: {
      y: {
        beginAtZero: true,
        ticks: {
          stepSize: 1,
          font: { size: 11 },
          color: '#64748b',
        },
        grid: { color: 'rgba(100, 116, 139, 0.1)' },
      },
      x: {
        ticks: { font: { size: 11 }, color: '#64748b' },
        grid: { display: false },
      },
    },
  };

  const slaData = {
    labels: reportData?.sla_breakdown?.map(item => item.name || '') || [],
    datasets: [
      {
        data: reportData?.sla_breakdown?.map(item => item.count || 0) || [],
        backgroundColor: [
          'rgba(16, 185, 129, 0.85)',
          'rgba(245, 158, 11, 0.85)',
          'rgba(239, 68, 68, 0.85)',
        ],
        borderColor: '#ffffff',
        borderWidth: 2,
      },
    ],
  };

  const slaOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'bottom',
        labels: {
          font: { size: 10 },
          color: '#64748b',
          padding: 8,
          usePointStyle: true,
          pointStyle: 'circle',
        },
      },
      tooltip: {
        backgroundColor: '#ffffff',
        titleColor: '#1e293b',
        bodyColor: '#1e293b',
        borderColor: '#e2e8f0',
        borderWidth: 1,
        cornerRadius: 6,
        padding: 12,
        callbacks: {
          label: function(context) {
            const total = context.dataset.data.reduce((a, b) => a + b, 0);
            const percentage = total > 0 ? Math.round((context.parsed / total) * 100) : 0;
            return `${context.label}: ${context.parsed} (${percentage}%)`;
          }
        }
      }
    },
    cutout: '70%',
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96 bg-white border border-gray-200 rounded">
        <div className="w-8 h-8 border-2 border-blue-600 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <div className="w-full">
      {/* Header */}
      <div className="flex flex-wrap justify-between items-center gap-3 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Reports & Analytics</h1>
          <p className="text-sm text-gray-500 mt-1">Generate and view system reports</p>
        </div>
      </div>

      {error && (
        <div className="mb-4 p-3 bg-red-50 border border-red-200 text-red-700 text-sm font-medium rounded flex items-center gap-2">
          <svg className="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          {error}
        </div>
      )}

      {/* Report Configuration */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-4 mb-6">
        <div className="lg:col-span-2 bg-white border border-gray-200 rounded p-5 shadow-sm">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Report Configuration</h3>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Report Type</label>
              <select
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 bg-white text-gray-900 rounded text-sm focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
              >
                {reportTypes.map((type) => (
                  <option key={type.value} value={type.value}>{type.label}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Date Range</label>
              <select
                value={dateRange}
                onChange={(e) => setDateRange(e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 bg-white text-gray-900 rounded text-sm focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
              >
                <option value="7">Last 7 Days</option>
                <option value="30">Last 30 Days</option>
                <option value="90">Last 90 Days</option>
                <option value="180">Last 6 Months</option>
                <option value="365">Last Year</option>
              </select>
            </div>
            <button
              onClick={handleGenerateReport}
              disabled={generating}
              className="w-full px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {generating ? (
                <span className="flex items-center gap-2">
                  <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Generating...
                </span>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Generate Report
                </>
              )}
            </button>
          </div>
        </div>

        <div className="lg:col-span-2 bg-white border border-gray-200 rounded p-5 shadow-sm">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Quick Stats</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-blue-50 p-3 rounded border border-blue-200">
              <p className="text-2xl font-bold text-blue-600">{reportData?.total_tickets || 0}</p>
              <p className="text-xs text-gray-600 font-medium">Total Tickets</p>
            </div>
            <div className="bg-emerald-50 p-3 rounded border border-emerald-200">
              <p className="text-2xl font-bold text-emerald-600">{reportData?.resolved_tickets || 0}</p>
              <p className="text-xs text-gray-600 font-medium">Resolved</p>
            </div>
            <div className="bg-amber-50 p-3 rounded border border-amber-200">
              <p className="text-2xl font-bold text-amber-600">{reportData?.open_tickets || 0}</p>
              <p className="text-xs text-gray-600 font-medium">Open</p>
            </div>
            <div className="bg-red-50 p-3 rounded border border-red-200">
              <p className="text-2xl font-bold text-red-600">{reportData?.sla_breached || 0}</p>
              <p className="text-xs text-gray-600 font-medium">SLA Breached</p>
            </div>
          </div>
        </div>
      </div>

      {/* Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-6">
        <div className="bg-white border border-gray-200 rounded p-5 shadow-sm">
          <h3 className="text-sm font-semibold text-gray-900 mb-4">Ticket Trend</h3>
          <div className="h-52">
            {reportData?.ticket_trend?.length > 0 ? (
              <Line data={ticketTrendData} options={ticketTrendOptions} />
            ) : (
              <p className="text-gray-500 text-sm text-center py-4">No trend data available</p>
            )}
          </div>
        </div>

        <div className="bg-white border border-gray-200 rounded p-5 shadow-sm">
          <h3 className="text-sm font-semibold text-gray-900 mb-4">Status Distribution</h3>
          <div className="h-52">
            {reportData?.status_breakdown?.length > 0 ? (
              <Doughnut data={statusChartData} options={statusChartOptions} />
            ) : (
              <p className="text-gray-500 text-sm text-center py-4">No status data available</p>
            )}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div className="bg-white border border-gray-200 rounded p-5 shadow-sm">
          <h3 className="text-sm font-semibold text-gray-900 mb-4">Category Breakdown</h3>
          <div className="h-52">
            {reportData?.category_breakdown?.length > 0 ? (
              <Bar data={categoryChartData} options={categoryChartOptions} />
            ) : (
              <p className="text-gray-500 text-sm text-center py-4">No category data available</p>
            )}
          </div>
        </div>

        <div className="bg-white border border-gray-200 rounded p-5 shadow-sm">
          <h3 className="text-sm font-semibold text-gray-900 mb-4">SLA Status</h3>
          <div className="h-52">
            {reportData?.sla_breakdown?.length > 0 ? (
              <Doughnut data={slaData} options={slaOptions} />
            ) : (
              <p className="text-gray-500 text-sm text-center py-4">No SLA data available</p>
            )}
          </div>
        </div>
      </div>

      {/* Report Modal */}
      {showReportModal && reportData && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded shadow-xl max-w-6xl w-full max-h-[90vh] overflow-y-auto p-6">
            <div className="flex justify-between items-center mb-4 pb-3 border-b border-gray-200 no-print">
              <h3 className="text-xl font-bold text-gray-900">Report Preview</h3>
              <div className="flex gap-2 flex-wrap">
                <button
                  onClick={handleExportPDF}
                  disabled={generating}
                  className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded transition-colors"
                >
                  {generating ? 'Generating...' : 'Export PDF'}
                </button>
                <button
                  onClick={handleExportExcel}
                  disabled={generating}
                  className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-medium rounded transition-colors"
                >
                  {generating ? 'Generating...' : 'Export Excel'}
                </button>
                <button
                  onClick={() => window.print()}
                  className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded transition-colors"
                >
                  Print
                </button>
                <button
                  onClick={() => setShowReportModal(false)}
                  className="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-700 text-sm font-medium rounded transition-colors"
                >
                  Close
                </button>
              </div>
            </div>

            <div id="report-content" className="space-y-6">
              <div className="text-center border-b border-gray-200 pb-4">
                <h4 className="text-lg font-bold text-gray-900">System Report</h4>
                <p className="text-sm text-gray-500">Generated on {new Date().toLocaleString()}</p>
                <p className="text-sm text-gray-500">Report Type: {reportTypes.find(t => t.value === reportType)?.label}</p>
                <p className="text-sm text-gray-500">Date Range: {dateRange} days</p>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-gray-50 p-3 rounded border border-gray-200">
                  <p className="text-2xl font-bold text-blue-600">{reportData.total_tickets || 0}</p>
                  <p className="text-xs text-gray-500">Total Tickets</p>
                </div>
                <div className="bg-gray-50 p-3 rounded border border-gray-200">
                  <p className="text-2xl font-bold text-emerald-600">{reportData.resolved_tickets || 0}</p>
                  <p className="text-xs text-gray-500">Resolved</p>
                </div>
                <div className="bg-gray-50 p-3 rounded border border-gray-200">
                  <p className="text-2xl font-bold text-amber-600">{reportData.open_tickets || 0}</p>
                  <p className="text-xs text-gray-500">Open</p>
                </div>
                <div className="bg-gray-50 p-3 rounded border border-gray-200">
                  <p className="text-2xl font-bold text-red-600">{reportData.sla_breached || 0}</p>
                  <p className="text-xs text-gray-500">SLA Breached</p>
                </div>
              </div>

              {reportData.status_breakdown && reportData.status_breakdown.length > 0 && (
                <div>
                  <h5 className="text-sm font-semibold text-gray-700 mb-2">Status Breakdown</h5>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                    {reportData.status_breakdown.map((item) => (
                      <div key={item.name} className="flex justify-between p-2 bg-gray-50 rounded border border-gray-200">
                        <span className="text-sm text-gray-600">{formatStatusLabel(item.name)}</span>
                        <span className="text-sm font-bold text-blue-600">{item.count}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {reportData.category_breakdown && reportData.category_breakdown.length > 0 && (
                <div>
                  <h5 className="text-sm font-semibold text-gray-700 mb-2">Category Breakdown</h5>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
                    {reportData.category_breakdown.map((item) => (
                      <div key={item.name} className="flex justify-between p-2 bg-gray-50 rounded border border-gray-200">
                        <span className="text-sm text-gray-600">{item.name || 'Uncategorized'}</span>
                        <span className="text-sm font-bold text-blue-600">{item.count}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {reportData.sla_breakdown && reportData.sla_breakdown.length > 0 && (
                <div>
                  <h5 className="text-sm font-semibold text-gray-700 mb-2">SLA Breakdown</h5>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
                    {reportData.sla_breakdown.map((item) => (
                      <div key={item.name} className="flex justify-between p-2 bg-gray-50 rounded border border-gray-200">
                        <span className="text-sm text-gray-600">{item.name}</span>
                        <span className="text-sm font-bold text-blue-600">{item.count}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {reportData.ticket_trend && reportData.ticket_trend.length > 0 && (
                <div>
                  <h5 className="text-sm font-semibold text-gray-700 mb-2">Ticket Trend</h5>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                    {reportData.ticket_trend.map((item) => (
                      <div key={item.date} className="flex justify-between p-2 bg-gray-50 rounded border border-gray-200">
                        <span className="text-sm text-gray-600">{item.day || item.date}</span>
                        <span className="text-sm font-bold text-blue-600">{item.count || 0}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="border-t border-gray-200 pt-4 text-center text-xs text-gray-400">
                <p>Generated by {user?.full_name || user?.username} on {new Date().toLocaleString()}</p>
              </div>
            </div>
          </div>
        </div>
      )}

      <style jsx="true">{`
        @media print {
          body * {
            visibility: hidden;
          }
          #report-content, #report-content * {
            visibility: visible;
          }
          #report-content {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            padding: 20px;
            background: white;
          }
          .no-print {
            display: none !important;
          }
        }
      `}</style>
    </div>
  );
};

export default AdminReports;